{
 "title": "Mantis Node",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Mantis Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Block Number",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "app_sync_block_number_gauge", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Block Transactions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "app_sync_block_transactions_gauge",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Block time",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(app_sync_block_timeBetweenParent_seconds_gauge)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Block Difficulty",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "app_sync_block_difficulty_gauge",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Block Gas Limit",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "app_sync_block_gasLimit_gauge", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Block Gas Used",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "app_sync_block_gasUsed_gauge", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Transactions Pool Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "app_transactions_pool_size_gauge",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Discovery Found Peers",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "app_network_discovery_foundPeers_gauge",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Discovery Blacklisted Peers",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "app_network_peers_blacklisted_gauge",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Incoming Peers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "app_network_peers_incoming_handshaked_gauge",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Outgoing Peers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "app_network_peers_outgoing_handshaked_gauge",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "RPC Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(app_json_rpc_methods_error_counter_total[15m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "RPC Exceptions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(app_json_rpc_methods_exception_counter_total[15m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "RPC Not Found",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(app_json_rpc_notfound_calls_counter_total[15m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "RPC Max Time",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(app_json_rpc_methods_timer_seconds_max)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Log Events",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(logback_appender_total[5m])",
     "legendFormat": "{{instance}}:{{level}}"
    }
   ]
  },
  {
   "title": "Pending Peers",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "app_network_peers_pending_gauge",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Memory Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    { "expr": "jvm_memory_bytes_used", "legendFormat": "{{instance}}:{{area}}" }
   ]
  },
  {
   "title": "Threads Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_threads_current", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}